### PR TITLE
Use Google Cloud Build instead of Travis CI

### PR DESCRIPTION
**Pull request by pshevtsov**

### CODE REVIEW

**Review by prees1 — APPROVED** [review]
LGTM 👍

**Review by jmariomejiap — APPROVED** [review]
Looks good to me 🚀

**Comment by jmariomejiap** [comment]
How do we access the cloud build dashboard. I tried to log in with my `mario@tidalmigrations.com` email but didn't see anything. are we using a different account?

**Comment by pshevtsov** [comment]
> How do we access the cloud build dashboard. I tried to log in with my `mario@tidalmigrations.com` email but didn't see anything. are we using a different account?

@jmariomejiap added you to the GCP project, you should receive an email.

**Comment by jmariomejiap** [comment]
> > How do we access the cloud build dashboard. I tried to log in with my `mario@tidalmigrations.com` email but didn't see anything. are we using a different account?
> 
> @jmariomejiap added you to the GCP project, you should receive an email.

Got it, thanks 👍

**Pull request merged**
