### PR TITLE
V5.4.18

### PR DESCRIPTION
**Pull request by jmariomejiap**
This PR introduces 2 changes.

1. It fixes an issue with the JRE version. I created a ticket for this issue.
```
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsupportedClassVersionError: com/castsoftware/highlight/HighlightAutomation has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
at java.lang.ClassLoader.defineClass1(Native Method)
at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
at java.net.URLClassLoader.defineClass(URLClassLoader.java:473)
at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
at java.security.AccessController.doPrivileged(Native Method)
at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:601)
```

Later, I stumbled into this from CAST where they "document" 🙄  the breaking issue.  you can see it [here](https://help.castsoftware.com/hc/en-us/articles/4912570259730-CAST-HIGHLIGHT-CLI-JRE-upgrade-to-11-needed-for-the-HL-Command-Line-version-5-4-9). 

Basically, CAST has made some changes and it now requires Java 11.  So we are upgrading our open-jdk from 8 -> 11.

2. It brings the documentation improvements @SamDesmondKing made on  [this PR](https://github.com/tidalmigrations/cast-highlight-docker/pull/46)

I have tested it and it works just fine 🥳 

image

image

### CODE REVIEW

**Comment by MichaelMULLER** [comment]
Sorry for that @jmariomejiap, it was only indicated in the Command Line's README and announced on our Twitter account on April 11th https://twitter.com/HighlightProdUp/status/1513512421561884676

**Review by SamDesmondKing — APPROVED** [review]
Nice catch Mario, I ran it too and everything looks good.

**Review by pranavmalaviya — APPROVED** [review]
Looks good @jmariomejiap. Great improvement on the docs too! 🚀

**Comment by MichaelMULLER** [comment]
Thanks @jmariomejiap I have updated this page accordingly.

**Pull request merged**
